name: dartflash-escape
description: This game was ported from Adobe Flash to HTML5 by using Dart and the dartflash library.
dependencies:
  dartflash:
    git:
      url: https://github.com/bp74/dartflash.git
      ref: master


