name: stagexl_escape
author: Bernhard Pichler
description: This game was ported from Adobe Flash to HTML5 by using Dart and the dartflash library.
homepage: http://www.stagexl.org/games/escape/escape.html
dependencies:
  browser: any
  stagexl:
    git: https://github.com/bp74/StageXL.git
